#!/bin/sh

if [ -f /usr/Hseries/configs/upgrade.tar ];then
    cd /usr/Hseries/configs/
    tar xvf upgrade.tar
    if [ -d upgrade ];then
        if [ $? == 0 ];then
            cd upgrade
            chmod +x ./upgrade.sh
            ./upgrade.sh
            cd ../
            upgrade_done=true
        fi
        rm upgrade -rf
    fi
    if [ $upgrade_done ];then
        rm upgrade.tar -rf
    fi
fi
sync
