#!/bin/sh
ulimit -d unlimited
ulimit -c unlimited

/usr/Hseries/bin/lock_sil9136.sh &

mount tmpfs -t tmpfs /tmp
export PATH="/usr/nova/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/lib:/usr/lib:/usr/nova/lib:$LD_LIBRARY_PATH"


if [ -d /usr/H9-MVR ];then
    rm /usr/H9-MVR -r
fi

if [ ! -f /sbin/ip ];then
    ln -s /bin/ip /sbin/ip                                         
fi                                                                 

if [ ! -d /var/db ];then                                           
    mkdir /var/db -p                                               
fi 

sync

if [ -f /usr/Hseries/configs/mvr_fpga.bin ];then
    /usr/Hseries/bin/load_fpga_img.sh /usr/Hseries/configs/mvr_fpga.bin
    mv /usr/Hseries/configs/mvr_fpga.bin /usr/nova/etc/fpga/
fi
sync

grep "^sshd" /etc/passwd >& /dev/null
if [ $? -ne 0 ]
then
    adduser sshd -H -D
fi
if [ ! -f "/etc/ssh/ssh_host_dsa_key" ];then
    ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ""
fi
if [ ! -f "/etc/ssh/ssh_host_rsa_key" ];then
    ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
fi

chown root /var/empty
chmod 644 /var/empty/
/sbin/sshd
sync

cd /usr/Hseries/bin/
./load6208.sh /usr/Hseries/configs/CDCM6208_Settings_hidoo_H9_MVR_Y4_200MHz_Y3Y5Y6Y7_162.5MHz.ini cdcm6208-0 
./load6208.sh /usr/Hseries/configs/CDCM6208_Settings_hidoo_H9_MVR_Y4-Y7_148.5MHz.ini cdcm6208-1 

#wait 6208-0(1 seconds) 6208-1(3 seconds) latches clock then reload fpga
sleep 3 
/usr/nova/bin/enable_arm_access.sh
/usr/nova/bin/enable_fpga_cfg.sh

try_times=0
while [ $(cat /sys/class/gpio/gpio93/value) != 1 -a $try_times -lt 600 ] #1分钟
do
    sleep 0.1
    try_times=$(($try_times+1))
done

if [ $try_times -ge 600 ];then
    exit 0
fi

# wait fpga loaded then reconnect 9136(hdmi)
# echo 2 > /sys/devices/platform/i2c-gpio.0/i2c-0/i2c-3/3-0039/sii9136_reconnect/sii9136_reconnect_sel
killall lock_sil9136.sh

 

echo 0 > /sys/class/gpio/export
echo 1 > /sys/class/gpio/export
echo 2 > /sys/class/gpio/export
echo 3 > /sys/class/gpio/export
echo 4 > /sys/class/gpio/export
echo 5 > /sys/class/gpio/export
echo 6 > /sys/class/gpio/export
echo 7 > /sys/class/gpio/export

echo in > /sys/class/gpio/gpio0/direction
echo in > /sys/class/gpio/gpio1/direction
echo in > /sys/class/gpio/gpio2/direction
echo in > /sys/class/gpio/gpio3/direction
echo in > /sys/class/gpio/gpio4/direction
echo in > /sys/class/gpio/gpio5/direction
echo in > /sys/class/gpio/gpio6/direction
echo in > /sys/class/gpio/gpio7/direction

ID0=$(cat /sys/class/gpio/gpio0/value)
ID1=$(cat /sys/class/gpio/gpio1/value)
ID2=$(cat /sys/class/gpio/gpio2/value)
ID3=$(cat /sys/class/gpio/gpio3/value)
ID4=$(cat /sys/class/gpio/gpio4/value)
ID5=$(cat /sys/class/gpio/gpio5/value)
ID6=$(cat /sys/class/gpio/gpio6/value)
ID7=$(cat /sys/class/gpio/gpio7/value)

SLOT_ID=$(( $ID7<<7|$ID6<<6 | $ID5<<5 | $ID4<<4 | $ID3<<3 | $ID2<<2 | $ID1<<1 | $ID0))
if [ $SLOT_ID == 201 -o $SLOT_ID == 10 ];then
    SLOT_ID=21
fi
echo $SLOT_ID > /dev/slot_id

echo 88 > /sys/class/gpio/export
echo in > /sys/class/gpio/gpio88/direction

#wait fpga init logic
sleep 2
/usr/Hseries/bin/guardian.sh /usr/Hseries/bin/start_video.sh >/dev/null 2>&1 &
/usr/Hseries/bin/guardian.sh "/usr/Hseries/bin/spi_master -t 1" > /dev/null 2>&1 &


